sudo: required
language: python
matrix:
  include:
  - python: 2.7
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: 3.7
    dist: xenial
  - python: pypy
install:
  - scripts/install-on-travis.sh
script:
  - make check
  - make test
after_success:
  - coveralls
branches:
  except:
    - /^[0-9]/
